#!/bin/bash

_path="$HOME/.passwords/passwords"
_root_path="$HOME/.passwords/"
username=${2}
comment=${3:-"null"}
length=${4:-"12"}

case ${1} in
"-a")
	{
		characters="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()"
		password=$(head /dev/urandom | tr -dc "$characters" | head -c "$length")
		echo $password | xsel --clipboard
		echo -e "$username:$password:$comment\n" | tee -a ${_path}
		echo "-----------------------------------" >>${_path}
		gpg --yes -e --recipient "alenine74@proton.me" ${_path}
	}
	;;
"-u")
	{
		match_count=$(grep -c "${username}" "${_path}")
		if [ "$match_count" -gt 1 ]; then
			echo "Which password do you want?"
			grep "${username}" "${_path}"
			read -r x
			grep "${x}" "${_path}" | cut -d':' -f2 | xsel --clipboard
		elif [ "$match_count" -eq 1 ]; then
			grep "${username}" "${_path}" | cut -d':' -f2 | xsel --clipboard
		else
			echo "There is no username"
		fi
	}
	;;
"-git")
	{
		echo "This will add and push this commit to your repo"
		git -C "${_root_path}" add "${_path}.gpg"
		echo "Enter your commit message:"
		read -r a
		comment=${a:-"update"}
		git -C "${_root_path}" commit -m "${comment}"
		echo "Enter your repository URL:"
		read -r u
		url=${u:-"git@github.com:alenine74/aleni.git"}
		git -C "${_root_path}" remote add origin "${url}" 2>/dev/null
		git -C "${_root_path}" push -u origin master
	}
	;;
*)
	echo "Usage: $0 {-a|-u|-git} username [comment] [length]"
	exit 1
	;;
esac
